version: '3'
services:
    nginx:
        build:
            context: ./
            dockerfile: docker/nginx.docker
        volumes:
            - ./:/var/www
        ports:
            - "8088:80"
        links:
            - php-fpm
    php-fpm:
        build:
            context: ./
            dockerfile: docker/php-fpm.docker
            args:
              - USER_ID
              - GROUP_ID
        volumes:
            - ./:/var/www
        links:
            - mysql
        environment:
            PHP_IDE_CONFIG: "serverName=laravel-testing"
            PHP_XDEBUG_ENABLED: 1
            DB_HOST: "mysql"
            DB_PORT: "3306"
    mysql:
        image: mysql:5.7
        volumes:
            - ./docker/mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_USER=app"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=app"
        ports:
            - "33061:3306"
    node:
      image: node:12.18.2-alpine
      volumes:
        - ./:/var/www
      working_dir: /var/www
      tty: true
